---
version: '3'
 
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk-1
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
      - "zookeeper-1:${IP_ADDR}"
      - "zookeeper-2:${IP_ADDR}"
      - "zookeeper-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
  zookeeper-2:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk-2
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
      - "zookeeper-1:${IP_ADDR}"
      - "zookeeper-2:${IP_ADDR}"
      - "zookeeper-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
  zookeeper-3:
    image: confluentinc/cp-zookeeper:latest
    container_name: zk-3
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:22888:23888;zookeeper-2:32888:33888;zookeeper-3:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
      - "zookeeper-1:${IP_ADDR}"
      - "zookeeper-2:${IP_ADDR}"
      - "zookeeper-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
 
  kafka-1:
    image: confluentinc/cp-kafka:latest
    container_name: kaf-1
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: ${IP_ADDR}:22181,${IP_ADDR}:32181,${IP_ADDR}:4218                                                                                              1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDR}:19092
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
      - "zookeeper-1:${IP_ADDR}"
      - "zookeeper-2:${IP_ADDR}"
      - "zookeeper-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
  kafka-2:
    image: confluentinc/cp-kafka:latest
    container_name: kaf-2
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${IP_ADDR}:22181,${IP_ADDR}:32181,${IP_ADDR}:4218                                                                                              1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDR}:29092
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
  kafka-3:
    image: confluentinc/cp-kafka:latest
    container_name: kaf-3
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: ${IP_ADDR}:22181,${IP_ADDR}:32181,${IP_ADDR}:4218                                                                                              1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_ADDR}:39092
    extra_hosts:
      - "moby:${IP_ADDR}"
      - "kafka-1:${IP_ADDR}"
      - "kafka-2:${IP_ADDR}"
      - "kafka-3:${IP_ADDR}"
      - "zookeeper-1:${IP_ADDR}"
      - "zookeeper-2:${IP_ADDR}"
      - "zookeeper-3:${IP_ADDR}"
    restart: unless-stopped
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    environment:
      KAFKA_BROKERCONNECT: "${IP_ADDR}:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringD                                                                                              eduplication -noverify"
    depends_on:
      - "kafka-2"
    network_mode: host
    volumes:
       - /etc/localtime:/etc/localtime:ro
 
 
  kafka-exporter:
    container_name: kafka-exporter
    image: danielqsj/kafka-exporter
    restart: unless-stopped
    command: ["--kafka.server=${IP_ADDR}:19092"]
    command: ["--kafka.server=${IP_ADDR}:29092"]
    command: ["--kafka.server=${IP_ADDR}:39092"]
    depends_on:
      - "kafka-2"
    network_mode: host
    volumes:
       - /etc/localtime:/etc/localtime:ro
